// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(_Context))]
    [Migration("20250328203830_creacion_bd")]
    partial class creacion_bd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Database.Tables.Tab_Usuarios", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaCreacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaModificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("FechaModificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Uui")
                        .HasColumnType("char(36)")
                        .HasColumnName("uui");

                    b.HasKey("Id");

                    b.ToTable("TabUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            Activo = true,
                            Contrasena = "$2a$06$GyfGGOV6EKo49KPjBqwyQ.lwqtjk7w1gSkORVdZ6ltn0KTPzd9Ehm",
                            FechaCreacion = new DateTime(2025, 3, 28, 14, 38, 29, 726, DateTimeKind.Local).AddTicks(5100),
                            FechaModificacion = new DateTime(2025, 3, 28, 14, 38, 29, 726, DateTimeKind.Local).AddTicks(5110),
                            Nombre = "ADMINISTRADOR",
                            Usuario = "admin",
                            Uui = new Guid("07ed28a5-f0c9-4c91-ae18-fa0d7300e29c")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
